//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using System.Ext;
using System.Ext.Xml;
using Ws.ServiceModel;
using Ws.Services.Mtom;
using Ws.Services.Serialization;
using XmlElement = Ws.Services.Xml.WsXmlNode;
using XmlAttribute = Ws.Services.Xml.WsXmlAttribute;
using XmlConvert = Ws.Services.Serialization.WsXmlConvert;

namespace schemas.singularbiogentics.com
{
    
    
    [ServiceContract(Namespace="http://schemas.singularbiogentics.com/")]
    public interface IMyServiceToo
    {
        
        [OperationContract(Action="http://schemas.singularbiogentics.com/IMyServiceToo/Start", IsOneWay=true)]
        void Start();
    }
    
    [ServiceContract(Namespace="http://schemas.singularbiogentics.com/")]
    public interface IMyService
    {
        
        [OperationContract(Action="http://schemas.singularbiogentics.com/IMyService/Start", IsOneWay=true)]
        void Start();
    }
}
