//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Text;
using System.Xml;
using Dpws.Device;
using Dpws.Device.Services;
using Ws.Services;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;
using Ws.Services.Binding;
using Ws.Services.Soap;

namespace Algae.Schemas.MyServiceToo
{
    
    
    public class MyServiceToo : DpwsHostedService
    {
        
        private IMyServiceToo m_service;
        
        public MyServiceToo(IMyServiceToo service, ProtocolVersion version) : 
                base(version)
        {
            // Set the service implementation properties
            m_service = service;

            // Set base service properties
            ServiceNamespace = new WsXmlNamespace("mys", "http://Algae.Schemas/MyServiceToo");
            ServiceID = "urn:uuid:1a9790d9-230f-4b5d-b74f-ba217497b989";
            ServiceTypeName = "MyServiceToo";

            // Add service types here
            ServiceOperations.Add(new WsServiceOperation("http://algae.schemas/MyServiceToo/IMyServiceToo", "Start"));

            // Add event sources here
        }
        
        public MyServiceToo(IMyServiceToo service) : 
                this(service, new ProtocolVersion10())
        {
        }
        
        public virtual WsMessage Start(WsMessage request)
        {
            request.Reader.Dispose();
            request.Reader = null;

            // Call service operation to process request.
            m_service.Start();

            // Return a OneWayResponse message for oneway messages
            return WsMessage.CreateOneWayResponse();
        }
    }
}
