//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using System.Ext;
using System.Ext.Xml;
using Ws.ServiceModel;
using Ws.Services.Mtom;
using Ws.Services.Serialization;
using XmlElement = Ws.Services.Xml.WsXmlNode;
using XmlAttribute = Ws.Services.Xml.WsXmlAttribute;
using XmlConvert = Ws.Services.Serialization.WsXmlConvert;

namespace tempuri.org
{
    
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class IsConnected
    {
    }
    
    public class IsConnectedDataContractSerializer : DataContractSerializer
    {
        
        public IsConnectedDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public IsConnectedDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            IsConnected IsConnectedField = null;
            if (IsParentStartElement(reader, false, true))
            {
                IsConnectedField = new IsConnected();
                reader.Read();
                reader.ReadEndElement();
            }
            return IsConnectedField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            IsConnected IsConnectedField = ((IsConnected)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class IsConnectedResponse
    {
        
        [DataMember(Order=0, IsRequired=false)]
        public bool IsConnectedResult;
    }
    
    public class IsConnectedResponseDataContractSerializer : DataContractSerializer
    {
        
        public IsConnectedResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public IsConnectedResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            IsConnectedResponse IsConnectedResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                IsConnectedResponseField = new IsConnectedResponse();
                reader.Read();
                if (IsChildStartElement(reader, "IsConnectedResult", false, false))
                {
                    reader.Read();
                    IsConnectedResponseField.IsConnectedResult = XmlConvert.ToBoolean(reader.ReadString());
                    reader.ReadEndElement();
                }
                reader.ReadEndElement();
            }
            return IsConnectedResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            IsConnectedResponse IsConnectedResponseField = ((IsConnectedResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                if (WriteChildElement(writer, "IsConnectedResult", false, false, IsConnectedResponseField.IsConnectedResult))
                {
                    writer.WriteString(XmlConvert.ToString(IsConnectedResponseField.IsConnectedResult));
                    writer.WriteEndElement();
                }
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class Send
    {
        
        [DataMember(Order=0, IsNillable=true, IsRequired=false)]
        public schemas.datacontract.org.Algae.WcfServiceLibrary.ArrayOfSbcData data;
    }
    
    public class SendDataContractSerializer : DataContractSerializer
    {
        
        public SendDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public SendDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            Send SendField = null;
            if (IsParentStartElement(reader, false, true))
            {
                SendField = new Send();
                reader.Read();
                schemas.datacontract.org.Algae.WcfServiceLibrary.ArrayOfSbcDataDataContractSerializer dataDCS = new schemas.datacontract.org.Algae.WcfServiceLibrary.ArrayOfSbcDataDataContractSerializer("data", "http://tempuri.org/", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary");
                dataDCS.BodyParts = this.BodyParts;
                SendField.data = ((schemas.datacontract.org.Algae.WcfServiceLibrary.ArrayOfSbcData)(dataDCS.ReadObject(reader)));
                reader.ReadEndElement();
            }
            return SendField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            Send SendField = ((Send)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                schemas.datacontract.org.Algae.WcfServiceLibrary.ArrayOfSbcDataDataContractSerializer dataDCS = new schemas.datacontract.org.Algae.WcfServiceLibrary.ArrayOfSbcDataDataContractSerializer("data", "http://tempuri.org/", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary");
                dataDCS.BodyParts = this.BodyParts;
                dataDCS.WriteObject(writer, SendField.data);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class SendResponse
    {
    }
    
    public class SendResponseDataContractSerializer : DataContractSerializer
    {
        
        public SendResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public SendResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            SendResponse SendResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                SendResponseField = new SendResponse();
                reader.Read();
                reader.ReadEndElement();
            }
            return SendResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            SendResponse SendResponseField = ((SendResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [ServiceContract(Namespace="http://tempuri.org/")]
    [PolicyAssertion(Namespace="http://www.w3.org/2006/05/addressing/wsdl", Name="UsingAddressing", PolicyID="WS2007HttpBinding_IPersistenceSvc_policy")]
    public interface IIPersistenceSvc
    {
        
        [OperationContract(Action="http://tempuri.org/IPersistenceSvc/IsConnected")]
        IsConnectedResponse IsConnected(IsConnected req);
        
        [OperationContract(Action="http://tempuri.org/IPersistenceSvc/Send")]
        SendResponse Send(Send req);
    }
}
namespace schemas.datacontract.org.Algae.WcfServiceLibrary
{
    
    
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary")]
    public enum DataType
    {
        
        [EnumMember()]
        Bool,
        
        [EnumMember()]
        Byte,
        
        [EnumMember()]
        Sbyte,
        
        [EnumMember()]
        Char,
        
        [EnumMember()]
        Decimal,
        
        [EnumMember()]
        Double,
        
        [EnumMember()]
        Float,
        
        [EnumMember()]
        Int,
        
        [EnumMember()]
        Uint,
        
        [EnumMember()]
        Long,
        
        [EnumMember()]
        Ulong,
        
        [EnumMember()]
        Object,
        
        [EnumMember()]
        Short,
        
        [EnumMember()]
        Ushort,
        
        [EnumMember()]
        String,
    }
    
    public class DataTypeDataContractSerializer : DataContractSerializer
    {
        
        public DataTypeDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public DataTypeDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            DataType DataTypeField = 0;
            if (IsParentStartElement(reader, false, true))
            {
                DataTypeField = new DataType();
				switch(reader.ReadString())
				{
					case "Bool":
                		DataTypeField = DataType.Bool;
                		break;
					case "Byte":
                		DataTypeField = DataType.Byte;
                		break;
					case "Sbyte":
                		DataTypeField = DataType.Sbyte;
                		break;
					case "Char":
                		DataTypeField = DataType.Char;
                		break;
					case "Decimal":
                		DataTypeField = DataType.Decimal;
                		break;
					case "Double":
                		DataTypeField = DataType.Double;
                		break;
					case "Float":
                		DataTypeField = DataType.Float;
                		break;
					case "Int":
                		DataTypeField = DataType.Int;
                		break;
					case "Uint":
                		DataTypeField = DataType.Uint;
                		break;
					case "Long":
                		DataTypeField = DataType.Long;
                		break;
					case "Ulong":
                		DataTypeField = DataType.Ulong;
                		break;
					case "Object":
                		DataTypeField = DataType.Object;
                		break;
					case "Short":
                		DataTypeField = DataType.Short;
                		break;
					case "Ushort":
                		DataTypeField = DataType.Ushort;
                		break;
					case "String":
                		DataTypeField = DataType.String;
                		break;
					default:
                		throw new XmlException();
				}
                reader.ReadEndElement();
            }
            return DataTypeField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            DataType DataTypeField = ((DataType)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
				switch(DataTypeField)
				{
					case DataType.Bool:
                		writer.WriteString("Bool");
                		break;
					case DataType.Byte:
                		writer.WriteString("Byte");
                		break;
					case DataType.Sbyte:
                		writer.WriteString("Sbyte");
                		break;
					case DataType.Char:
                		writer.WriteString("Char");
                		break;
					case DataType.Decimal:
                		writer.WriteString("Decimal");
                		break;
					case DataType.Double:
                		writer.WriteString("Double");
                		break;
					case DataType.Float:
                		writer.WriteString("Float");
                		break;
					case DataType.Int:
                		writer.WriteString("Int");
                		break;
					case DataType.Uint:
                		writer.WriteString("Uint");
                		break;
					case DataType.Long:
                		writer.WriteString("Long");
                		break;
					case DataType.Ulong:
                		writer.WriteString("Ulong");
                		break;
					case DataType.Object:
                		writer.WriteString("Object");
                		break;
					case DataType.Short:
                		writer.WriteString("Short");
                		break;
					case DataType.Ushort:
                		writer.WriteString("Ushort");
                		break;
					case DataType.String:
                		writer.WriteString("String");
                		break;
					default:
                		throw new XmlException();
				}
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary")]
    public enum DataMetric
    {
        
        [EnumMember()]
        Celsius,
        
        [EnumMember()]
        OnOff,
        
        [EnumMember()]
        Moles,
    }
    
    public class DataMetricDataContractSerializer : DataContractSerializer
    {
        
        public DataMetricDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public DataMetricDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            DataMetric DataMetricField = 0;
            if (IsParentStartElement(reader, false, true))
            {
                DataMetricField = new DataMetric();
				switch(reader.ReadString())
				{
					case "Celsius":
                		DataMetricField = DataMetric.Celsius;
                		break;
					case "OnOff":
                		DataMetricField = DataMetric.OnOff;
                		break;
					case "Moles":
                		DataMetricField = DataMetric.Moles;
                		break;
					default:
                		throw new XmlException();
				}
                reader.ReadEndElement();
            }
            return DataMetricField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            DataMetric DataMetricField = ((DataMetric)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
				switch(DataMetricField)
				{
					case DataMetric.Celsius:
                		writer.WriteString("Celsius");
                		break;
					case DataMetric.OnOff:
                		writer.WriteString("OnOff");
                		break;
					case DataMetric.Moles:
                		writer.WriteString("Moles");
                		break;
					default:
                		throw new XmlException();
				}
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary")]
    public class SbcData
    {
        
        [DataMember(Order=0, IsNillable=true, IsRequired=false)]
        public string SensorGuid;
        
        [DataMember(Order=1, IsNillable=true, IsRequired=false)]
        public string Data;
        
        [DataMember(Order=2, IsRequired=false)]
        public System.DateTime Timestamp;
        
        [DataMember(Order=3, IsRequired=false)]
        public DataType DataType;
        
        [DataMember(Order=4, IsRequired=false)]
        public DataMetric DataMetric;
    }
    
    public class SbcDataDataContractSerializer : DataContractSerializer
    {
        
        public SbcDataDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public SbcDataDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            SbcData SbcDataField = null;
            if (IsParentStartElement(reader, false, true))
            {
                SbcDataField = new SbcData();
                reader.Read();
                if (IsChildStartElement(reader, "SensorGuid", true, false))
                {
                    reader.Read();
                    SbcDataField.SensorGuid = reader.ReadString();
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "Data", true, false))
                {
                    reader.Read();
                    SbcDataField.Data = reader.ReadString();
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "Timestamp", false, false))
                {
                    reader.Read();
                    SbcDataField.Timestamp = XmlConvert.ToDateTime(reader.ReadString());
                    reader.ReadEndElement();
                }
                reader.Read();
				switch(reader.Value)
				{
					case "Bool":
                		SbcDataField.DataType = DataType.Bool;
                		break;
					case "Byte":
                		SbcDataField.DataType = DataType.Byte;
                		break;
					case "Sbyte":
                		SbcDataField.DataType = DataType.Sbyte;
                		break;
					case "Char":
                		SbcDataField.DataType = DataType.Char;
                		break;
					case "Decimal":
                		SbcDataField.DataType = DataType.Decimal;
                		break;
					case "Double":
                		SbcDataField.DataType = DataType.Double;
                		break;
					case "Float":
                		SbcDataField.DataType = DataType.Float;
                		break;
					case "Int":
                		SbcDataField.DataType = DataType.Int;
                		break;
					case "Uint":
                		SbcDataField.DataType = DataType.Uint;
                		break;
					case "Long":
                		SbcDataField.DataType = DataType.Long;
                		break;
					case "Ulong":
                		SbcDataField.DataType = DataType.Ulong;
                		break;
					case "Object":
                		SbcDataField.DataType = DataType.Object;
                		break;
					case "Short":
                		SbcDataField.DataType = DataType.Short;
                		break;
					case "Ushort":
                		SbcDataField.DataType = DataType.Ushort;
                		break;
					case "String":
                		SbcDataField.DataType = DataType.String;
                		break;
					default:
                		throw new XmlException();
				}
                reader.Read();
                    switch(reader.Value)
                    {
	                    case "Celsius":
                            SbcDataField.DataMetric = DataMetric.Celsius;
                            break;
	                    case "OnOff":
                            SbcDataField.DataMetric = DataMetric.OnOff;
                            break;
	                    case "Moles":
                            SbcDataField.DataMetric = DataMetric.Moles;
                            break;
	                    default:
                            throw new XmlException();
                    }
                reader.ReadEndElement();
            }
            return SbcDataField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            SbcData SbcDataField = ((SbcData)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                if (WriteChildElement(writer, "SensorGuid", true, false, SbcDataField.SensorGuid))
                {
                    writer.WriteString(SbcDataField.SensorGuid);
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "Data", true, false, SbcDataField.Data))
                {
                    writer.WriteString(SbcDataField.Data);
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "Timestamp", false, false, SbcDataField.Timestamp))
                {
                    writer.WriteString(XmlConvert.ToString(SbcDataField.Timestamp));
                    writer.WriteEndElement();
                }
                DataTypeDataContractSerializer DataTypeDCS = new DataTypeDataContractSerializer("DataType", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary");
                DataTypeDCS.BodyParts = this.BodyParts;
                DataTypeDCS.WriteObject(writer, SbcDataField.DataType);
                DataMetricDataContractSerializer DataMetricDCS = new DataMetricDataContractSerializer("DataMetric", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary");
                DataMetricDCS.BodyParts = this.BodyParts;
                DataMetricDCS.WriteObject(writer, SbcDataField.DataMetric);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary")]
    public class ArrayOfSbcData
    {
        
        [DataMember(Order=0, IsNillable=true, IsRequired=false)]
        public SbcData[] SbcData;
    }
    
    public class ArrayOfSbcDataDataContractSerializer : DataContractSerializer
    {
        
        public ArrayOfSbcDataDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public ArrayOfSbcDataDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            ArrayOfSbcData ArrayOfSbcDataField = null;
            if (IsParentStartElement(reader, false, true))
            {
                ArrayOfSbcDataField = new ArrayOfSbcData();
                reader.Read();
                SbcDataDataContractSerializer SbcDataDCS = new SbcDataDataContractSerializer("SbcData", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary");
                System.Collections.ArrayList SbcData_List = new System.Collections.ArrayList();
                for (int i = 0; (i > -1); i = (i + 1))
                {
                    if (!IsChildStartElement(reader, "SbcData", false, false))
                    {
                        ArrayOfSbcDataField.SbcData = new SbcData[SbcData_List.Count];
                        SbcData_List.CopyTo(ArrayOfSbcDataField.SbcData);
						break;
                    }
                    SbcData_List.Add(((SbcData)(SbcDataDCS.ReadObject(reader))));
                }
                reader.ReadEndElement();
            }
            return ArrayOfSbcDataField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            ArrayOfSbcData ArrayOfSbcDataField = ((ArrayOfSbcData)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                SbcDataDataContractSerializer SbcDataDCS = new SbcDataDataContractSerializer("SbcData", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary", "http://schemas.datacontract.org/2004/07/Algae.WcfServiceLibrary");
                for (int i = 0; (i < ArrayOfSbcDataField.SbcData.Length); i = (i + 1))
                {
                    SbcDataDCS.WriteObject(writer, ArrayOfSbcDataField.SbcData[i]);
                }
                writer.WriteEndElement();
            }
            return;
        }
    }
}
