//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using Dpws.Client;
using Dpws.Client.Discovery;
using Dpws.Client.Eventing;
using Ws.Services;
using Ws.Services.Utilities;
using Ws.Services.Binding;
using Ws.Services.Soap;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;

namespace tempuri.org
{
    
    
    public class IPersistenceSvcClientProxy : DpwsClient
    {
        
        private IRequestChannel m_requestChannel = null;
        
        public IPersistenceSvcClientProxy(Binding binding, ProtocolVersion version) : 
                base(binding, version)
        {

            // Set client endpoint address
            m_requestChannel = m_localBinding.CreateClientChannel(new ClientBindingContext(m_version));
        }
        
        public virtual IsConnectedResponse IsConnected(IsConnected req)
        {

            // Create request header
            String action;
            action = "http://tempuri.org/IPersistenceSvc/IsConnected";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            IsConnectedDataContractSerializer reqDcs;
            reqDcs = new IsConnectedDataContractSerializer("IsConnected", "http://tempuri.org/");
            request.Serializer = reqDcs;
            request.Method = "IsConnected";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            IsConnectedResponseDataContractSerializer respDcs;
            respDcs = new IsConnectedResponseDataContractSerializer("IsConnectedResponse", "http://tempuri.org/");
            IsConnectedResponse resp;
            resp = ((IsConnectedResponse)(respDcs.ReadObject(response.Reader)));
            response.Reader.Dispose();
            response.Reader = null;
            return resp;
        }
        
        public virtual SendResponse Send(Send req)
        {

            // Create request header
            String action;
            action = "http://tempuri.org/IPersistenceSvc/Send";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            SendDataContractSerializer reqDcs;
            reqDcs = new SendDataContractSerializer("Send", "http://tempuri.org/");
            request.Serializer = reqDcs;
            request.Method = "Send";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            SendResponseDataContractSerializer respDcs;
            respDcs = new SendResponseDataContractSerializer("SendResponse", "http://tempuri.org/");
            SendResponse resp;
            resp = ((SendResponse)(respDcs.ReadObject(response.Reader)));
            response.Reader.Dispose();
            response.Reader = null;
            return resp;
        }
    }
}
