//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Text;
using System.Xml;
using Dpws.Device;
using Dpws.Device.Services;
using Ws.Services;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;
using Ws.Services.Binding;
using Ws.Services.Soap;

namespace Gadgeteer.WCF.Sample
{
    
    
    public class IService1 : DpwsHostedService
    {
        
        private IIService1 m_service;
        
        public IService1(IIService1 service, ProtocolVersion version) : 
                base(version)
        {
            // Set the service implementation properties
            m_service = service;

            // Set base service properties
            ServiceNamespace = new WsXmlNamespace("ise", "http://Gadgeteer.WCF.Sample");
            ServiceID = "urn:uuid:f8a07e07-0a03-44e4-ba4b-16146c33d215";
            ServiceTypeName = "IService1";

            // Add service types here
            ServiceOperations.Add(new WsServiceOperation("http://Gadgeteer.WCF.Sample/IService1", "GetData"));
            ServiceOperations.Add(new WsServiceOperation("http://Gadgeteer.WCF.Sample/IService1", "GetDataUsingDataContract"));

            // Add event sources here
        }
        
        public IService1(IIService1 service) : 
                this(service, new ProtocolVersion10())
        {
        }
        
        public virtual WsMessage GetData(WsMessage request)
        {
            // Build request object
            GetDataDataContractSerializer reqDcs;
            reqDcs = new GetDataDataContractSerializer("GetData", "http://Gadgeteer.WCF.Sample");
            GetData req;
            req = ((GetData)(reqDcs.ReadObject(request.Reader)));

            // Create response object
            // Call service operation to process request and return response.
            GetDataResponse resp;
            resp = m_service.GetData(req);

            // Create response header
            WsWsaHeader respHeader = new WsWsaHeader("http://Gadgeteer.WCF.Sample/IService1/GetDataResponse", request.Header.MessageID, m_version.AnonymousUri, null, null, null);
            WsMessage response = new WsMessage(respHeader, resp, WsPrefix.Wsdp);

            // Create response serializer
            GetDataResponseDataContractSerializer respDcs;
            respDcs = new GetDataResponseDataContractSerializer("GetDataResponse", "http://Gadgeteer.WCF.Sample");
            response.Serializer = respDcs;
            return response;
        }
        
        public virtual WsMessage GetDataUsingDataContract(WsMessage request)
        {
            // Build request object
            GetDataUsingDataContractDataContractSerializer reqDcs;
            reqDcs = new GetDataUsingDataContractDataContractSerializer("GetDataUsingDataContract", "http://Gadgeteer.WCF.Sample");
            GetDataUsingDataContract req;
            req = ((GetDataUsingDataContract)(reqDcs.ReadObject(request.Reader)));

            // Create response object
            // Call service operation to process request and return response.
            GetDataUsingDataContractResponse resp;
            resp = m_service.GetDataUsingDataContract(req);

            // Create response header
            WsWsaHeader respHeader = new WsWsaHeader("http://Gadgeteer.WCF.Sample/IService1/GetDataUsingDataContractResponse", request.Header.MessageID, m_version.AnonymousUri, null, null, null);
            WsMessage response = new WsMessage(respHeader, resp, WsPrefix.Wsdp);

            // Create response serializer
            GetDataUsingDataContractResponseDataContractSerializer respDcs;
            respDcs = new GetDataUsingDataContractResponseDataContractSerializer("GetDataUsingDataContractResponse", "http://Gadgeteer.WCF.Sample");
            response.Serializer = respDcs;
            return response;
        }
    }
}
