//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using Dpws.Client;
using Dpws.Client.Discovery;
using Dpws.Client.Eventing;
using Ws.Services;
using Ws.Services.Utilities;
using Ws.Services.Binding;
using Ws.Services.Soap;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;

namespace Gadgeteer.WCF.Sample
{
    
    
    public class IService1ClientProxy : DpwsClient
    {
        
        private IRequestChannel m_requestChannel = null;
        
        public IService1ClientProxy(Binding binding, ProtocolVersion version) : 
                base(binding, version)
        {

            // Set client endpoint address
            m_requestChannel = m_localBinding.CreateClientChannel(new ClientBindingContext(m_version));
        }
        
        public virtual GetDataResponse GetData(GetData req)
        {

            // Create request header
            String action;
            action = "http://Gadgeteer.WCF.Sample/IService1/GetData";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            GetDataDataContractSerializer reqDcs;
            reqDcs = new GetDataDataContractSerializer("GetData", "http://Gadgeteer.WCF.Sample");
            request.Serializer = reqDcs;
            request.Method = "GetData";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            GetDataResponseDataContractSerializer respDcs;
            respDcs = new GetDataResponseDataContractSerializer("GetDataResponse", "http://Gadgeteer.WCF.Sample");
            GetDataResponse resp;
            resp = ((GetDataResponse)(respDcs.ReadObject(response.Reader)));
            return resp;
        }
        
        public virtual GetDataUsingDataContractResponse GetDataUsingDataContract(GetDataUsingDataContract req)
        {

            // Create request header
            String action;
            action = "http://Gadgeteer.WCF.Sample/IService1/GetDataUsingDataContract";
            WsWsaHeader header;
            header = new WsWsaHeader(action, null, EndpointAddress, m_version.AnonymousUri, null, null);
            WsMessage request = new WsMessage(header, req, WsPrefix.None);

            // Create request serializer
            GetDataUsingDataContractDataContractSerializer reqDcs;
            reqDcs = new GetDataUsingDataContractDataContractSerializer("GetDataUsingDataContract", "http://Gadgeteer.WCF.Sample");
            request.Serializer = reqDcs;
            request.Method = "GetDataUsingDataContract";


            // Send service request
            m_requestChannel.Open();
            WsMessage response = m_requestChannel.Request(request);
            m_requestChannel.Close();

            // Process response
            GetDataUsingDataContractResponseDataContractSerializer respDcs;
            respDcs = new GetDataUsingDataContractResponseDataContractSerializer("GetDataUsingDataContractResponse", "http://Gadgeteer.WCF.Sample");
            GetDataUsingDataContractResponse resp;
            resp = ((GetDataUsingDataContractResponse)(respDcs.ReadObject(response.Reader)));
            return resp;
        }
    }
}
