//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Text;
using System.Xml;
using Dpws.Device;
using Dpws.Device.Services;
using Ws.Services;
using Ws.Services.WsaAddressing;
using Ws.Services.Xml;
using Ws.Services.Binding;
using Ws.Services.Soap;

namespace tempuri.org
{
    
    
    public class IDuperSvc : DpwsHostedService
    {
        
        private IIDuperSvc m_service;
        
        public IDuperSvc(IIDuperSvc service, ProtocolVersion version) : 
                base(version)
        {
            // Set the service implementation properties
            m_service = service;

            // Set base service properties
            ServiceNamespace = new WsXmlNamespace("idu", "http://tempuri.org/");
            ServiceID = "urn:uuid:f248bb60-286c-4592-b2f1-1f9147767d7f";
            ServiceTypeName = "IDuperSvc";

            // Add service types here
            ServiceOperations.Add(new WsServiceOperation("http://tempuri.org/IDuperSvc", "IsActive"));
            ServiceOperations.Add(new WsServiceOperation("http://tempuri.org/IDuperSvc", "GetData"));
            ServiceOperations.Add(new WsServiceOperation("http://tempuri.org/IDuperSvc", "GetDataUsingDataContract"));

            // Add event sources here
        }
        
        public IDuperSvc(IIDuperSvc service) : 
                this(service, new ProtocolVersion10())
        {
        }
        
        public virtual WsMessage IsActive(WsMessage request)
        {
            // Build request object
            IsActiveDataContractSerializer reqDcs;
            reqDcs = new IsActiveDataContractSerializer("IsActive", "http://tempuri.org/");
            IsActive req;
            req = ((IsActive)(reqDcs.ReadObject(request.Reader)));
            request.Reader.Dispose();
            request.Reader = null;

            // Create response object
            // Call service operation to process request and return response.
            IsActiveResponse resp;
            resp = m_service.IsActive(req);

            // Create response header
            WsWsaHeader respHeader = new WsWsaHeader("http://tempuri.org/IDuperSvc/IsActiveResponse", request.Header.MessageID, m_version.AnonymousUri, null, null, null);
            WsMessage response = new WsMessage(respHeader, resp, WsPrefix.Wsdp);

            // Create response serializer
            IsActiveResponseDataContractSerializer respDcs;
            respDcs = new IsActiveResponseDataContractSerializer("IsActiveResponse", "http://tempuri.org/");
            response.Serializer = respDcs;
            return response;
        }
        
        public virtual WsMessage GetData(WsMessage request)
        {
            // Build request object
            GetDataDataContractSerializer reqDcs;
            reqDcs = new GetDataDataContractSerializer("GetData", "http://tempuri.org/");
            GetData req;
            req = ((GetData)(reqDcs.ReadObject(request.Reader)));
            request.Reader.Dispose();
            request.Reader = null;

            // Create response object
            // Call service operation to process request and return response.
            GetDataResponse resp;
            resp = m_service.GetData(req);

            // Create response header
            WsWsaHeader respHeader = new WsWsaHeader("http://tempuri.org/IDuperSvc/GetDataResponse", request.Header.MessageID, m_version.AnonymousUri, null, null, null);
            WsMessage response = new WsMessage(respHeader, resp, WsPrefix.Wsdp);

            // Create response serializer
            GetDataResponseDataContractSerializer respDcs;
            respDcs = new GetDataResponseDataContractSerializer("GetDataResponse", "http://tempuri.org/");
            response.Serializer = respDcs;
            return response;
        }
        
        public virtual WsMessage GetDataUsingDataContract(WsMessage request)
        {
            // Build request object
            GetDataUsingDataContractDataContractSerializer reqDcs;
            reqDcs = new GetDataUsingDataContractDataContractSerializer("GetDataUsingDataContract", "http://tempuri.org/");
            GetDataUsingDataContract req;
            req = ((GetDataUsingDataContract)(reqDcs.ReadObject(request.Reader)));
            request.Reader.Dispose();
            request.Reader = null;

            // Create response object
            // Call service operation to process request and return response.
            GetDataUsingDataContractResponse resp;
            resp = m_service.GetDataUsingDataContract(req);

            // Create response header
            WsWsaHeader respHeader = new WsWsaHeader("http://tempuri.org/IDuperSvc/GetDataUsingDataContractResponse", request.Header.MessageID, m_version.AnonymousUri, null, null, null);
            WsMessage response = new WsMessage(respHeader, resp, WsPrefix.Wsdp);

            // Create response serializer
            GetDataUsingDataContractResponseDataContractSerializer respDcs;
            respDcs = new GetDataUsingDataContractResponseDataContractSerializer("GetDataUsingDataContractResponse", "http://tempuri.org/");
            response.Serializer = respDcs;
            return response;
        }
    }
}
