//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     .NET Micro Framework MFSvcUtil.Exe
//     Runtime Version:2.0.00001.0001
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Xml;
using System.Ext;
using System.Ext.Xml;
using Ws.ServiceModel;
using Ws.Services.Mtom;
using Ws.Services.Serialization;
using XmlElement = Ws.Services.Xml.WsXmlNode;
using XmlAttribute = Ws.Services.Xml.WsXmlAttribute;
using XmlConvert = Ws.Services.Serialization.WsXmlConvert;

namespace tempuri.org
{
    
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class IsActive
    {
    }
    
    public class IsActiveDataContractSerializer : DataContractSerializer
    {
        
        public IsActiveDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public IsActiveDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            IsActive IsActiveField = null;
            if (IsParentStartElement(reader, false, true))
            {
                IsActiveField = new IsActive();
                reader.Read();
                reader.ReadEndElement();
            }
            return IsActiveField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            IsActive IsActiveField = ((IsActive)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class IsActiveResponse
    {
        
        [DataMember(Order=0, IsRequired=false)]
        public bool IsActiveResult;
    }
    
    public class IsActiveResponseDataContractSerializer : DataContractSerializer
    {
        
        public IsActiveResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public IsActiveResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            IsActiveResponse IsActiveResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                IsActiveResponseField = new IsActiveResponse();
                reader.Read();
                if (IsChildStartElement(reader, "IsActiveResult", false, false))
                {
                    reader.Read();
                    IsActiveResponseField.IsActiveResult = XmlConvert.ToBoolean(reader.ReadString());
                    reader.ReadEndElement();
                }
                reader.ReadEndElement();
            }
            return IsActiveResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            IsActiveResponse IsActiveResponseField = ((IsActiveResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                if (WriteChildElement(writer, "IsActiveResult", false, false, IsActiveResponseField.IsActiveResult))
                {
                    writer.WriteString(XmlConvert.ToString(IsActiveResponseField.IsActiveResult));
                    writer.WriteEndElement();
                }
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class GetData
    {
        
        [DataMember(Order=0, IsRequired=false)]
        public int value;
    }
    
    public class GetDataDataContractSerializer : DataContractSerializer
    {
        
        public GetDataDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public GetDataDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            GetData GetDataField = null;
            if (IsParentStartElement(reader, false, true))
            {
                GetDataField = new GetData();
                reader.Read();
                if (IsChildStartElement(reader, "value", false, false))
                {
                    reader.Read();
                    GetDataField.value = XmlConvert.ToInt32(reader.ReadString());
                    reader.ReadEndElement();
                }
                reader.ReadEndElement();
            }
            return GetDataField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            GetData GetDataField = ((GetData)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                if (WriteChildElement(writer, "value", false, false, GetDataField.value))
                {
                    writer.WriteString(XmlConvert.ToString(GetDataField.value));
                    writer.WriteEndElement();
                }
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class GetDataResponse
    {
        
        [DataMember(Order=0, IsNillable=true, IsRequired=false)]
        public string GetDataResult;
    }
    
    public class GetDataResponseDataContractSerializer : DataContractSerializer
    {
        
        public GetDataResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public GetDataResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            GetDataResponse GetDataResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                GetDataResponseField = new GetDataResponse();
                reader.Read();
                if (IsChildStartElement(reader, "GetDataResult", true, false))
                {
                    reader.Read();
                    GetDataResponseField.GetDataResult = reader.ReadString();
                    reader.ReadEndElement();
                }
                reader.ReadEndElement();
            }
            return GetDataResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            GetDataResponse GetDataResponseField = ((GetDataResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                if (WriteChildElement(writer, "GetDataResult", true, false, GetDataResponseField.GetDataResult))
                {
                    writer.WriteString(GetDataResponseField.GetDataResult);
                    writer.WriteEndElement();
                }
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class GetDataUsingDataContract
    {
        
        [DataMember(Order=0, IsNillable=true, IsRequired=false)]
        public schemas.datacontract.org.FantasticoWcfServices.CompositeType composite;
    }
    
    public class GetDataUsingDataContractDataContractSerializer : DataContractSerializer
    {
        
        public GetDataUsingDataContractDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public GetDataUsingDataContractDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            GetDataUsingDataContract GetDataUsingDataContractField = null;
            if (IsParentStartElement(reader, false, true))
            {
                GetDataUsingDataContractField = new GetDataUsingDataContract();
                reader.Read();
                schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer compositeDCS = new schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer("composite", "http://tempuri.org/", "http://schemas.datacontract.org/2004/07/FantasticoWcfServices");
                compositeDCS.BodyParts = this.BodyParts;
                GetDataUsingDataContractField.composite = ((schemas.datacontract.org.FantasticoWcfServices.CompositeType)(compositeDCS.ReadObject(reader)));
                reader.ReadEndElement();
            }
            return GetDataUsingDataContractField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            GetDataUsingDataContract GetDataUsingDataContractField = ((GetDataUsingDataContract)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer compositeDCS = new schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer("composite", "http://tempuri.org/", "http://schemas.datacontract.org/2004/07/FantasticoWcfServices");
                compositeDCS.BodyParts = this.BodyParts;
                compositeDCS.WriteObject(writer, GetDataUsingDataContractField.composite);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [DataContract(Namespace="http://tempuri.org/")]
    public class GetDataUsingDataContractResponse
    {
        
        [DataMember(Order=0, IsNillable=true, IsRequired=false)]
        public schemas.datacontract.org.FantasticoWcfServices.CompositeType GetDataUsingDataContractResult;
    }
    
    public class GetDataUsingDataContractResponseDataContractSerializer : DataContractSerializer
    {
        
        public GetDataUsingDataContractResponseDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public GetDataUsingDataContractResponseDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            GetDataUsingDataContractResponse GetDataUsingDataContractResponseField = null;
            if (IsParentStartElement(reader, false, true))
            {
                GetDataUsingDataContractResponseField = new GetDataUsingDataContractResponse();
                reader.Read();
                schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer GetDataUsingDataContractResultDCS = new schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer("GetDataUsingDataContractResult", "http://tempuri.org/", "http://schemas.datacontract.org/2004/07/FantasticoWcfServices");
                GetDataUsingDataContractResultDCS.BodyParts = this.BodyParts;
                GetDataUsingDataContractResponseField.GetDataUsingDataContractResult = ((schemas.datacontract.org.FantasticoWcfServices.CompositeType)(GetDataUsingDataContractResultDCS.ReadObject(reader)));
                reader.ReadEndElement();
            }
            return GetDataUsingDataContractResponseField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            GetDataUsingDataContractResponse GetDataUsingDataContractResponseField = ((GetDataUsingDataContractResponse)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer GetDataUsingDataContractResultDCS = new schemas.datacontract.org.FantasticoWcfServices.CompositeTypeDataContractSerializer("GetDataUsingDataContractResult", "http://tempuri.org/", "http://schemas.datacontract.org/2004/07/FantasticoWcfServices");
                GetDataUsingDataContractResultDCS.BodyParts = this.BodyParts;
                GetDataUsingDataContractResultDCS.WriteObject(writer, GetDataUsingDataContractResponseField.GetDataUsingDataContractResult);
                writer.WriteEndElement();
            }
            return;
        }
    }
    
    [ServiceContract(Namespace="http://tempuri.org/")]
    [PolicyAssertion(Namespace="http://www.w3.org/2006/05/addressing/wsdl", Name="UsingAddressing", PolicyID="WS2007HttpBinding_IWonderfulSvc_policy")]
    public interface IIWonderfulSvc
    {
        
        [OperationContract(Action="http://tempuri.org/IWonderfulSvc/IsActive")]
        IsActiveResponse IsActive(IsActive req);
        
        [OperationContract(Action="http://tempuri.org/IWonderfulSvc/GetData")]
        GetDataResponse GetData(GetData req);
        
        [OperationContract(Action="http://tempuri.org/IWonderfulSvc/GetDataUsingDataContract")]
        GetDataUsingDataContractResponse GetDataUsingDataContract(GetDataUsingDataContract req);
    }
}
namespace schemas.datacontract.org.FantasticoWcfServices
{
    
    
    [DataContract(Namespace="http://schemas.datacontract.org/2004/07/FantasticoWcfServices")]
    public class CompositeType
    {
        
        [DataMember(Order=0, IsRequired=false)]
        public bool BoolValue;
        
        [DataMember(Order=1, IsNillable=true, IsRequired=false)]
        public string StringValue;
    }
    
    public class CompositeTypeDataContractSerializer : DataContractSerializer
    {
        
        public CompositeTypeDataContractSerializer(string rootName, string rootNameSpace) : 
                base(rootName, rootNameSpace)
        {
        }
        
        public CompositeTypeDataContractSerializer(string rootName, string rootNameSpace, string localNameSpace) : 
                base(rootName, rootNameSpace, localNameSpace)
        {
        }
        
        public override object ReadObject(XmlReader reader)
        {
            CompositeType CompositeTypeField = null;
            if (IsParentStartElement(reader, false, true))
            {
                CompositeTypeField = new CompositeType();
                reader.Read();
                if (IsChildStartElement(reader, "BoolValue", false, false))
                {
                    reader.Read();
                    CompositeTypeField.BoolValue = XmlConvert.ToBoolean(reader.ReadString());
                    reader.ReadEndElement();
                }
                if (IsChildStartElement(reader, "StringValue", true, false))
                {
                    reader.Read();
                    CompositeTypeField.StringValue = reader.ReadString();
                    reader.ReadEndElement();
                }
                reader.ReadEndElement();
            }
            return CompositeTypeField;
        }
        
        public override void WriteObject(XmlWriter writer, object graph)
        {
            CompositeType CompositeTypeField = ((CompositeType)(graph));
            if (WriteParentElement(writer, true, true, graph))
            {
                if (WriteChildElement(writer, "BoolValue", false, false, CompositeTypeField.BoolValue))
                {
                    writer.WriteString(XmlConvert.ToString(CompositeTypeField.BoolValue));
                    writer.WriteEndElement();
                }
                if (WriteChildElement(writer, "StringValue", true, false, CompositeTypeField.StringValue))
                {
                    writer.WriteString(CompositeTypeField.StringValue);
                    writer.WriteEndElement();
                }
                writer.WriteEndElement();
            }
            return;
        }
    }
}
